Logical: KdkOncologyModel
Id: kdk-oncology-model
Title: "KDK Onkologie – Quellmodell (BfArM MVGenomSeq)"
Description: "Quelltreues Logical Model der KDK-Onkologie-Einreichung (BfArM MVGenomSeq, Schema v2.3). Quelle fuer StructureMaps KDK -> MII KDS."
* ^status = #draft
* metaData 1..1 BackboneElement "metaData" "metaData"
* metaData.submission 1..1 BackboneElement "submission" "submission"
* metaData.submission.date 1..1 date "date" "Date of submission in ISO 8601 format YYYY-MM-DD"
* metaData.submission.type 1..1 code "type" "The options are: 'initial' for first submission, 'followup' is for followup submissions, 'addition' for additional submission, 'correction' for correction, 'test' is for technical testing of submissions"
* metaData.submission.submitterId 1..1 string "submitterId" "LE ID as specified by the BfArM or RVO"
* metaData.submission.genomicDataCenterId 0..1 string "genomicDataCenterId" "Id of the genomic data center, format GRZXXXnnn 9-digit assigned by BfArM. Not required in cases where diagnosisOd.libraryType = none."
* metaData.submission.clinicalDataNodeId 1..1 string "clinicalDataNodeId" "Id of the clinical data node, format KDKXXXnnn 9-digit assigned by BfArM"
* metaData.submission.diseaseType 1..1 code "diseaseType" "Type of disease (must be oncological or hereditary for Oncology object, rare for RareDiseasesObject)"
* metaData.mvConsent 1..1 BackboneElement "mvConsent" "mvConsent"
* metaData.mvConsent.presentationDate 0..1 date "presentationDate" "Date of delivery. Date (in ISO 8601 format YYYY-MM-DD) on which the Model Project Declaration of Participation was presented to the patient, unless identical to the date of signature"
* metaData.mvConsent.version 1..1 string "version" "Version of the declaration of participation. Name and version of the declaration of participation in the MV GenomSeq, e.g.: 'Patient Info TE Consent MVGenomSeq vers01'"
* metaData.mvConsent.scope 1..* BackboneElement "scope" "Modules of the consent to MV: must have at least a permit of mvSequencing"
* metaData.mvConsent.scope.type 1..1 code "type" "Consent or refusal to participate and consent, must be indicated for each option listed in the scope of consent."
* metaData.mvConsent.scope.date 1..1 date "date" "Date of signature of the pilot projects consent; in ISO 8601 format YYYY-MM-DD."
* metaData.mvConsent.scope.domain 1..1 code "domain" "Scope of consent or revocation."
* metaData.researchConsents 1..* BackboneElement "researchConsents" "Research consents. Multiple declarations of consent are possible! Must be assigned to the respective data sets."
* metaData.researchConsents.schemaVersion 0..1 code "schemaVersion" "Schema version of de.medizininformatikinitiative.kerndatensatz.consent"
* metaData.researchConsents.presentationDate 1..1 date "presentationDate" "Date of the delivery of the research consent in ISO 8601 format (YYYY-MM-DD)"
* metaData.researchConsents.scope 0..1 BackboneElement "scope" "Scope of the research consent in JSON format following the MII IG Consent v2025 FHIR schema. See 'https://www.medizininformatik-initiative.de/Kerndatensatz/KDS_Consent_V2025/MII-IG-Modul-Consent.html' and 'https://packag"
* metaData.researchConsents.noScopeJustification 0..1 code "noScopeJustification" "Justification if no scope object is present."
* metaData.coverageType 1..1 code "coverageType" "Health insurance providers"
* metaData.tanC 1..1 string "tanC" "Transaction number VNk"
* metaData.localCaseId 0..1 string "localCaseId" "A local case identifier of the Leistungserbringer to be able to track multiple submissions referring to the same index patient"
* metaData.gender 1..1 code "gender" "gender"
* metaData.birthDate 1..1 string "birthDate" "Date of birth without the day. Format YYYY-MM"
* metaData.addressAGS 1..1 string "addressAGS" "Official municipal code of the patient's residence."
* metaData.decisionToInclude 1..1 boolean "decisionToInclude" "Decision of the multidisciplinary case conference in the field of diagnostics on the inclusion of the insured person in the pilot project"
* metaData.molecularBoardDecisionDate 1..1 date "molecularBoardDecisionDate" "Date of the decision of the multidisciplinary case conference in the field of diagnostics on the inclusion of the insured person in the pilot project"
* metaData.rejectionJustification 0..1 code "rejectionJustification" "Reason for the negative decision"
* case 1..1 BackboneElement "case" "case"
* case.diagnosisOd 1..1 BackboneElement "diagnosisOd" "diagnosisOd"
* case.diagnosisOd.mainDiagnosis 1..1 Coding "mainDiagnosis" "A reference to a code defined by a terminology system Elements defined in Ancestors: id, extension"
* case.diagnosisOd.additionalDiagnoses 0..* Coding "additionalDiagnoses" "additionalDiagnoses"
* case.diagnosisOd.ecogPerformanceStatusScore 1..1 code "ecogPerformanceStatusScore" "ECOG Performance Status Score"
* case.diagnosisOd.germlineDiagnosisConfirmed 1..1 boolean "germlineDiagnosisConfirmed" "Indicates if a hereditary tumor syndrome diagnosis is confirmed."
* case.diagnosisOd.germlineDiagnoses 0..* Coding "germlineDiagnoses" "ICD-10-GM code ORPHA or AlphaID possible for the germline diagnosis"
* case.diagnosisOd.hpoTerms 0..* Coding "hpoTerms" "hpoTerms"
* case.diagnosisOd.histology 1..1 Coding "histology" "A reference to a code defined by a terminology system Elements defined in Ancestors: id, extension"
* case.diagnosisOd.topography 1..1 Coding "topography" "A reference to a code defined by a terminology system Elements defined in Ancestors: id, extension"
* case.diagnosisOd.grading 0..1 code "grading" "Differentiation grade"
* case.diagnosisOd.tnmClassifications 0..* Coding "tnmClassifications" "An array containing the TNM classification components (T, N, M), each represented using SNOMED CT codes."
* case.diagnosisOd.additionalClassification 0..* BackboneElement "additionalClassification" "Handles cases for additional classification or where the TNM classification system (AJCC or UICC) is unknown. This provides a string alternative to the SNOMED CT coding of TNM, using a system 'TNM'."
* case.diagnosisOd.additionalClassification.system 0..1 string "system" "The classification system used, e.g., 'TNM'."
* case.diagnosisOd.additionalClassification.key 0..1 string "key" "key"
* case.diagnosisOd.libraryType 1..1 code "libraryType" "Art der Sequenzierung oder none, falls keine Sequenzierung indiziert"
* case.diagnosisOd.diagnosticAssessment 0..1 code "diagnosticAssessment" "Evaluation of genetic diagnostics (only for HT)."
* case.priorDiagnostics 0..* BackboneElement "priorDiagnostics" "priorDiagnostics"
* case.priorDiagnostics.type 1..1 code "type" "type"
* case.priorDiagnostics.date 0..1 date "date" "date"
* case.priorDiagnostics.simpleVariants 0..* BackboneElement "simpleVariants" "simpleVariants"
* case.priorDiagnostics.simpleVariants.gene 1..1 Coding "gene" "A reference to a code defined by a terminology system Elements defined in Ancestors: id, extension"
* case.priorDiagnostics.simpleVariants.transcript 0..1 Coding "transcript" "A reference to a code defined by a terminology system Elements defined in Ancestors: id, extension"
* case.priorDiagnostics.simpleVariants.dnaChange 1..1 string "dnaChange" "HGVSc (Change at DNA Level). e.g. c.173_187del"
* case.priorDiagnostics.simpleVariants.proteinChange 0..1 string "proteinChange" "HGVSp (Change at Protein Level). e.g. p.V600E"
* case.priorDiagnostics.simpleVariants.variantTypes 0..* Coding "variantTypes" "Attribute values should be derived from the Sequence Ontology. Refer to the specific subset under 'sequence_variant' at http://www.sequenceontology.org/miso for allowed codes."
* case.priorDiagnostics.complexVariants 0..* string "complexVariants" "complexVariants"
* case.priorProcedures 0..* BackboneElement "priorProcedures" "priorProcedures"
* case.priorProcedures.treatmentType 1..1 code "treatmentType" "treatmentType"
* case.priorProcedures.intention 0..1 code "intention" "intention"
* case.priorProcedures.substances 0..* BackboneElement "substances" "substances"
* case.priorProcedures.substances.code 0..1 Coding "code" "A reference to a code defined by a terminology system Elements defined in Ancestors: id, extension"
* case.priorProcedures.substances.name 0..1 string "name" "Name of active substance is required when only pharmacological class is given."
* case.priorProcedures.therapyStartDate 1..1 date "therapyStartDate" "Date when the therapy started. If the day is unknown, use the 15th of the month."
* case.priorProcedures.therapyEndDate 0..1 date "therapyEndDate" "therapyEndDate"
* case.priorProcedures.terminationReasonOBDS 0..1 code "terminationReasonOBDS" "terminationReasonOBDS"
* case.priorProcedures.therapyResponseDate 0..1 date "therapyResponseDate" "therapyResponseDate"
* case.priorProcedures.therapyResponse 0..1 code "therapyResponse" "therapyResponse"
* molecular 0..1 BackboneElement "molecular" "Schema for molecular report in oncology, including various variant types."
* molecular.smallVariants 0..* BackboneElement "smallVariants" "smallVariants"
* molecular.smallVariants.identifier 1..1 string "identifier" "A base identifier type."
* molecular.smallVariants.genomicSource 1..1 code "genomicSource" "Source of the genomic material."
* molecular.smallVariants.gene 1..1 Coding "gene" "A reference to a code defined by a terminology system Elements defined in Ancestors: id, extension"
* molecular.smallVariants.transcriptId 0..1 Coding "transcriptId" "A reference to a code defined by a terminology system Elements defined in Ancestors: id, extension"
* molecular.smallVariants.dnaChange 1..1 string "dnaChange" "DNA level alteration (HGVSc)."
* molecular.smallVariants.proteinChange 0..1 string "proteinChange" "Protein level alteration (HGVSp)."
* molecular.smallVariants.chromosome 1..1 code "chromosome" "chromosome"
* molecular.smallVariants.startPosition 1..1 integer "startPosition" "Start coordinate in GRCh38 VCF-style."
* molecular.smallVariants.endPosition 1..1 integer "endPosition" "End coordinate in GRCh38 VCF-style."
* molecular.smallVariants.ref 1..1 string "ref" "ref sequence VCF-style."
* molecular.smallVariants.alt 1..1 string "alt" "alt/observed sequence VCF-style."
* molecular.smallVariants.variantTypes 0..* Coding "variantTypes" "Alteration type from Sequence Ontology."
* molecular.smallVariants.localization 1..1 code "localization" "Localization of molecular alteration."
* molecular.smallVariants.loh 0..1 boolean "loh" "Loss of heterozygosity."
* molecular.copyNumberVariants 0..* BackboneElement "copyNumberVariants" "copyNumberVariants"
* molecular.copyNumberVariants.identifier 1..1 string "identifier" "A base identifier type."
* molecular.copyNumberVariants.genomicSource 1..1 code "genomicSource" "Source of the genomic material."
* molecular.copyNumberVariants.cnvType 1..1 code "cnvType" "Type of copy number alteration."
* molecular.copyNumberVariants.gene 0..1 Coding "gene" "A reference to a code defined by a terminology system Elements defined in Ancestors: id, extension"
* molecular.copyNumberVariants.chromosome 0..1 code "chromosome" "chromosome"
* molecular.copyNumberVariants.endPosition 0..1 integer "endPosition" "End position on the chromosome (HG38-Position)."
* molecular.copyNumberVariants.startPosition 0..1 integer "startPosition" "Start position on the chromosome (HG38-Position)."
* molecular.copyNumberVariants.localization 1..1 code "localization" "Localization of molecular alteration."
* molecular.structuralVariants 0..* BackboneElement "structuralVariants" "structuralVariants"
* molecular.structuralVariants.identifier 1..1 string "identifier" "A base identifier type."
* molecular.structuralVariants.genomicSource 1..1 code "genomicSource" "Source of the genomic material."
* molecular.structuralVariants.geneA 1..1 Coding "geneA" "A reference to a code defined by a terminology system Elements defined in Ancestors: id, extension"
* molecular.structuralVariants.geneB 1..1 Coding "geneB" "A reference to a code defined by a terminology system Elements defined in Ancestors: id, extension"
* molecular.structuralVariants.structureType 1..1 code "structureType" "Type of structural variant."
* molecular.structuralVariants.description 0..1 string "description" "Description of the structural variant (HGVS/ISCN)."
* molecular.structuralVariants.sequenceType 1..1 code "sequenceType" "sequenceType"
* molecular.structuralVariants.localization 1..1 code "localization" "Localization of molecular alteration."
* molecular.expressionVariants 0..* BackboneElement "expressionVariants" "expressionVariants"
* molecular.expressionVariants.identifier 1..1 string "identifier" "A base identifier type."
* molecular.expressionVariants.gene 1..1 Coding "gene" "A reference to a code defined by a terminology system Elements defined in Ancestors: id, extension"
* molecular.expressionVariants.expressionType 1..1 code "expressionType" "Expression level of mRNA."
* molecular.expressionVariants.reference 1..1 string "reference" "e.g. reference cohort of 400 patients"
* molecular.complexBiomarkers 0..* BackboneElement "complexBiomarkers" "complexBiomarkers"
* molecular.complexBiomarkers.identifier 1..1 string "identifier" "A base identifier type."
* molecular.complexBiomarkers.ploidy 0..1 integer "ploidy" "ploidy"
* molecular.complexBiomarkers.tmb 0..1 decimal "tmb" "Tumor mutational burden. mut/MB"
* molecular.complexBiomarkers.hrdHigh 0..1 boolean "hrdHigh" "High homologous recombination deficiency."
* molecular.complexBiomarkers.lstHigh 0..1 boolean "lstHigh" "High large-scale transitions."
* molecular.complexBiomarkers.taiHigh 0..1 boolean "taiHigh" "High telomeric allelic imbalance."
* molecular.sbsSignatures 0..* BackboneElement "sbsSignatures" "sbsSignatures"
* molecular.sbsSignatures.identifier 1..1 string "identifier" "A base identifier type."
* molecular.sbsSignatures.version 0..1 string "version" "SBS Signatures Version"
* molecular.sbsSignatures.name 1..* string "name" "List of SBS Signatures. e.g. SBS 6"
* plan 0..1 BackboneElement "plan" "plan"
* plan.carePlanOd 1..1 BackboneElement "carePlanOd" "carePlanOd"
* plan.carePlanOd.molecularBoardDecisionDate 1..1 date "molecularBoardDecisionDate" "Date of case conference."
* plan.carePlanOd.studyRecommended 1..1 boolean "studyRecommended" "Recommendation to participate in a clinical study."
* plan.carePlanOd.counsellingRecommended 1..1 boolean "counsellingRecommended" "Recommendation for human genetic counseling."
* plan.carePlanOd.reEvaluationRecommended 1..1 boolean "reEvaluationRecommended" "Recommendation for diagnostic reevaluation."
* plan.carePlanOd.interventionRecommended 1..1 boolean "interventionRecommended" "Recommendation for an operation."
* plan.carePlanOd.suitableInterventions 0..* BackboneElement "suitableInterventions" "List of suitable interventions."
* plan.carePlanOd.suitableInterventions.interventionsIsRiskReducing 1..1 boolean "interventionsIsRiskReducing" "interventionsIsRiskReducing"
* plan.carePlanOd.suitableInterventions.interventionIsTherapeutic 1..1 boolean "interventionIsTherapeutic" "interventionIsTherapeutic"
* plan.carePlanOd.suitableInterventions.type 1..1 BackboneElement "type" "type"
* plan.carePlanOd.suitableInterventions.type.code 1..1 Coding "code" "A reference to a code defined by a terminology system Elements defined in Ancestors: id, extension"
* plan.carePlanOd.suitableInterventions.type.name 1..1 string "name" "name"
* plan.carePlanOd.otherRecommendations 0..* code "otherRecommendations" "otherRecommendations"
* plan.recommendedStudies 0..* BackboneElement "recommendedStudies" "recommendedStudies"
* plan.recommendedStudies.identifier 1..1 string "identifier" "A base identifier type."
* plan.recommendedStudies.register 1..1 code "register" "Study register."
* plan.recommendedStudies.name 1..1 string "name" "Study name."
* plan.recommendedStudies.id 1..1 string "id" "Study ID."
* plan.recommendedStudies.substances 0..* BackboneElement "substances" "substances"
* plan.recommendedStudies.substances.code 0..1 Coding "code" "A reference to a code defined by a terminology system Elements defined in Ancestors: id, extension"
* plan.recommendedStudies.substances.name 0..1 string "name" "Name of active substance is required when only pharmacological class is given."
* plan.recommendedStudies.evidenceLevel 1..1 code "evidenceLevel" "Evidence level."
* plan.recommendedStudies.evidenceLevelDetails 0..* code "evidenceLevelDetails" "evidenceLevelDetails"
* plan.recommendedStudies.priority 1..1 integer "priority" "Prioritization."
* plan.recommendedStudies.variants 0..* string "variants" "variants"
* plan.recommendedSystemicTherapies 0..* BackboneElement "recommendedSystemicTherapies" "recommendedSystemicTherapies"
* plan.recommendedSystemicTherapies.identifier 1..1 string "identifier" "A base identifier type."
* plan.recommendedSystemicTherapies.type 1..1 code "type" "Recommendation systemic therapy (outside of a clinical trial)"
* plan.recommendedSystemicTherapies.substances 1..* BackboneElement "substances" "substances"
* plan.recommendedSystemicTherapies.substances.code 1..1 Coding "code" "A reference to a code defined by a terminology system Elements defined in Ancestors: id, extension"
* plan.recommendedSystemicTherapies.substances.name 0..1 string "name" "Name of active substance is required when only pharmacological class is given."
* plan.recommendedSystemicTherapies.evidenceLevel 1..1 code "evidenceLevel" "Evidence level."
* plan.recommendedSystemicTherapies.evidenceLevelDetails 0..* code "evidenceLevelDetails" "evidenceLevelDetails"
* plan.recommendedSystemicTherapies.priority 1..1 integer "priority" "Prioritization."
* plan.recommendedSystemicTherapies.variants 0..* string "variants" "variants"
* plan.recommendedSystemicTherapies.therapeuticStrategy 1..1 code "therapeuticStrategy" "therapeuticStrategy"
* plan.preventiveMeasures 0..* BackboneElement "preventiveMeasures" "preventiveMeasures"
* plan.preventiveMeasures.identifier 1..1 string "identifier" "A base identifier type."
* plan.preventiveMeasures.type 1..1 string "type" "e.g. Breast Imaging (MRI, MGR, US) | Colonoscopy | Esophago-gastro-duodenoscopy"
* followUp 0..1 BackboneElement "followUp" "followUp"
* followUp.followUpOds 1..* BackboneElement "followUpOds" "Implementation of the therapy recommendation."
* followUp.followUpOds.followUpDate 1..1 date "followUpDate" "Date of the follow-up."
* followUp.followUpOds.metachroneDiagnoses 1..1 boolean "metachroneDiagnoses" "Indicates if metachronous tumors are observed."
* followUp.followUpOds.additionalDiagnoses 0..* Coding "additionalDiagnoses" "Diagnosis code and version for metachronous tumors."
* followUp.followUpOds.phenotypes 0..* Coding "phenotypes" "phenotypes"
* followUp.followUpOds.ecogPerformanceStatusScore 1..1 code "ecogPerformanceStatusScore" "ECOG Performance Status."
* followUp.followUpOds.vitalStatus 1..1 code "vitalStatus" "Vital status of the patient."
* followUp.followUpOds.lastContactDate 0..1 date "lastContactDate" "Date of the last contact with the patient."
* followUp.followUpOds.deathDate 0..1 date "deathDate" "Date of death."
* followUp.followUpOds.therapies 0..* BackboneElement "therapies" "therapies"
* followUp.followUpOds.therapies.reference 1..1 string "reference" "A base identifier type."
* followUp.followUpOds.therapies.therapyStartDate 1..1 date "therapyStartDate" "Date when the therapy started."
* followUp.followUpOds.therapies.therapyEndDate 0..1 date "therapyEndDate" "Date when the therapy ended."
* followUp.followUpOds.therapies.terminationReasonOBDS 0..1 code "terminationReasonOBDS" "terminationReasonOBDS"
* followUp.followUpOds.therapies.substances 0..* BackboneElement "substances" "substances"
* followUp.followUpOds.therapies.substances.code 0..1 Coding "code" "A reference to a code defined by a terminology system Elements defined in Ancestors: id, extension"
* followUp.followUpOds.therapies.substances.name 0..1 string "name" "Name of active substance is required when only pharmacological class is given."
* followUp.followUpOds.therapies.therapyResponse 0..1 code "therapyResponse" "Therapy response."
* followUp.followUpOds.therapies.therapyResponseDate 0..1 date "therapyResponseDate" "Date of therapy response evaluation."
* followUp.followUpOds.therapies.therapyResponseSource 0..1 string "therapyResponseSource" "Source of therapy response data."
* followUp.followUpOds.preventiveMeasures 0..* BackboneElement "preventiveMeasures" "preventiveMeasures"
* followUp.followUpOds.preventiveMeasures.reference 1..1 string "reference" "A base identifier type."
* followUp.followUpOds.preventiveMeasures.preventiveMeasureDate 1..1 date "preventiveMeasureDate" "Date of the preventive measure."
* followUp.followUpOds.preventiveMeasures.preventiveMeasureResult 1..1 code "preventiveMeasureResult" "Result of the preventive measure."
* followUp.followUpOds.preventiveMeasures.type 0..1 string "type" "type"
