Logical: KdkRareDiseasesModel
Id: kdk-rare-diseases-model
Title: "KDK Seltene Erkrankungen – Quellmodell (BfArM MVGenomSeq)"
Description: "Quelltreues Logical Model der KDK-Seltene-Erkrankungen-Einreichung (BfArM MVGenomSeq, Schema v2.3). Quelle fuer StructureMaps KDK -> MII KDS."
* ^status = #draft
* metaData 1..1 BackboneElement "metaData" "metaData"
* metaData.submission 1..1 BackboneElement "submission" "submission"
* metaData.submission.date 1..1 date "date" "Date of submission in ISO 8601 format YYYY-MM-DD"
* metaData.submission.type 1..1 code "type" "The options are: 'initial' for first submission, 'followup' is for followup submissions, 'addition' for additional submission, 'correction' for correction, 'test' is for technical testing of submissions"
* metaData.submission.submitterId 1..1 string "submitterId" "LE ID as specified by the BfArM or RVO"
* metaData.submission.genomicDataCenterId 0..1 string "genomicDataCenterId" "Id of the genomic data center, format GRZXXXnnn 9-digit assigned by BfArM. Not required in cases where diagnosisOd.libraryType = none."
* metaData.submission.clinicalDataNodeId 1..1 string "clinicalDataNodeId" "Id of the clinical data node, format KDKXXXnnn 9-digit assigned by BfArM"
* metaData.submission.diseaseType 1..1 code "diseaseType" "Type of disease (must be oncological or hereditary for Oncology object, rare for RareDiseasesObject)"
* metaData.mvConsent 1..1 BackboneElement "mvConsent" "mvConsent"
* metaData.mvConsent.presentationDate 0..1 date "presentationDate" "Date of delivery. Date (in ISO 8601 format YYYY-MM-DD) on which the Model Project Declaration of Participation was presented to the patient, unless identical to the date of signature"
* metaData.mvConsent.version 1..1 string "version" "Version of the declaration of participation. Name and version of the declaration of participation in the MV GenomSeq, e.g.: 'Patient Info TE Consent MVGenomSeq vers01'"
* metaData.mvConsent.scope 1..* BackboneElement "scope" "Modules of the consent to MV: must have at least a permit of mvSequencing"
* metaData.mvConsent.scope.type 1..1 code "type" "Consent or refusal to participate and consent, must be indicated for each option listed in the scope of consent."
* metaData.mvConsent.scope.date 1..1 date "date" "Date of signature of the pilot projects consent; in ISO 8601 format YYYY-MM-DD."
* metaData.mvConsent.scope.domain 1..1 code "domain" "Scope of consent or revocation."
* metaData.researchConsents 1..* BackboneElement "researchConsents" "Research consents. Multiple declarations of consent are possible! Must be assigned to the respective data sets."
* metaData.researchConsents.schemaVersion 0..1 code "schemaVersion" "Schema version of de.medizininformatikinitiative.kerndatensatz.consent"
* metaData.researchConsents.presentationDate 1..1 date "presentationDate" "Date of the delivery of the research consent in ISO 8601 format (YYYY-MM-DD)"
* metaData.researchConsents.scope 0..1 BackboneElement "scope" "Scope of the research consent in JSON format following the MII IG Consent v2025 FHIR schema. See 'https://www.medizininformatik-initiative.de/Kerndatensatz/KDS_Consent_V2025/MII-IG-Modul-Consent.html' and 'https://packag"
* metaData.researchConsents.noScopeJustification 0..1 code "noScopeJustification" "Justification if no scope object is present."
* metaData.coverageType 1..1 code "coverageType" "Health insurance providers"
* metaData.tanC 1..1 string "tanC" "Transaction number VNk"
* metaData.localCaseId 0..1 string "localCaseId" "A local case identifier of the Leistungserbringer to be able to track multiple submissions referring to the same index patient"
* metaData.gender 1..1 code "gender" "gender"
* metaData.birthDate 1..1 string "birthDate" "Date of birth without the day. Format YYYY-MM"
* metaData.addressAGS 1..1 string "addressAGS" "Official municipal code of the patient's residence."
* metaData.decisionToInclude 1..1 boolean "decisionToInclude" "Decision of the multidisciplinary case conference in the field of diagnostics on the inclusion of the insured person in the pilot project"
* metaData.molecularBoardDecisionDate 1..1 date "molecularBoardDecisionDate" "Date of the decision of the multidisciplinary case conference in the field of diagnostics on the inclusion of the insured person in the pilot project"
* metaData.rejectionJustification 0..1 code "rejectionJustification" "Reason for the negative decision"
* case 1..1 BackboneElement "case" "case"
* case.diagnosisRd 1..1 BackboneElement "diagnosisRd" "diagnosisRd"
* case.diagnosisRd.phenotypes 1..* Coding "phenotypes" "phenotypes"
* case.diagnosisRd.symptomOnsetDate 1..1 string "symptomOnsetDate" "Start of symptoms"
* case.diagnosisRd.molecularBoardDecisionDate 1..1 date "molecularBoardDecisionDate" "Case conference date"
* case.diagnosisRd.diagnosticExtent 1..1 code "diagnosticExtent" "Diagnostics recommendation"
* case.diagnosisRd.libraryType 1..1 code "libraryType" "Art der Sequenzierung oder none, falls keine Sequenzierung indiziert"
* case.diagnosisRd.diagnosticAssessment 1..1 code "diagnosticAssessment" "Assessment of genetic diagnostics"
* case.diagnosisRd.diagnoses 1..* Coding "diagnoses" "ICD10 mandatory, ORPHACode mandatory, Alpha ID mandatory"
* case.diagnosisRd.noMatchingCodeExists 0..1 boolean "noMatchingCodeExists" "Indicates whether a matching code exists."
* case.diagnosisRd.diagnosisGmfcs 0..1 code "diagnosisGmfcs" "Age-appropriate information, empty if not applicable"
* case.priorRds 0..* BackboneElement "priorRds" "priorRds"
* case.priorRds.genomicTestType 1..1 code "genomicTestType" "Type of diagnostics"
* case.priorRds.genomicStudyType 1..1 code "genomicStudyType" "genomicStudyType"
* case.priorRds.diagnosticDate 0..1 date "diagnosticDate" "Date of diagnostics"
* case.priorRds.diagnosticResult 1..1 code "diagnosticResult" "Result of diagnostics"
* case.priorRds.hospitalizationPeriods 1..1 code "hospitalizationPeriods" "Number of inpatient treatments in the last five years"
* case.priorRds.hospitalizationDuration 1..1 code "hospitalizationDuration" "Estimated duration of inpatient case-relevant pre-therapy in days"
* case.priorRds.zseContactDate 1..1 string "zseContactDate" "Month and year of first contact with a specialized center for rare diseases"
* molecular 0..1 BackboneElement "molecular" "molecular"
* molecular.structuralVariants 0..* BackboneElement "structuralVariants" "structuralVariants"
* molecular.structuralVariants.identifier 1..1 string "identifier" "A base identifier type."
* molecular.structuralVariants.genes 0..* BackboneElement "genes" "genes"
* molecular.structuralVariants.genes.code 0..1 string "code" "HGNC:ID"
* molecular.structuralVariants.localization 0..* BackboneElement "localization" "localization"
* molecular.structuralVariants.localization.code 0..1 code "code" "Gene localization"
* molecular.structuralVariants.gdnaChange 0..1 string "gdnaChange" "gDNA change (HGVS)."
* molecular.structuralVariants.cdnaChange 0..1 string "cdnaChange" "cDNA change (HGVS)."
* molecular.structuralVariants.proteinChange 0..1 string "proteinChange" "Protein change (HGVS)."
* molecular.structuralVariants.acmgClass 0..1 code "acmgClass" "ACMG class."
* molecular.structuralVariants.acmgCriteria 0..* BackboneElement "acmgCriteria" "acmgCriteria"
* molecular.structuralVariants.acmgCriteria.value 1..1 code "value" "value"
* molecular.structuralVariants.acmgCriteria.modifier 0..1 code "modifier" "modifier"
* molecular.structuralVariants.zygosity 0..1 code "zygosity" "Zygosity."
* molecular.structuralVariants.segregationAnalysis 0..1 code "segregationAnalysis" "Segregation analysis."
* molecular.structuralVariants.modeOfInheritance 0..1 code "modeOfInheritance" "modeOfInheritance"
* molecular.structuralVariants.diagnosticSignificance 0..1 code "diagnosticSignificance" "Significance for case."
* molecular.structuralVariants.externalId 0..1 string "externalId" "ClinVar variant ID."
* molecular.structuralVariants.publications 0..* string "publications" "Reference[Publication]. e.g., PubMed ID"
* molecular.structuralVariants.description 0..1 string "description" "ISCN Description."
* molecular.smallVariants 0..* BackboneElement "smallVariants" "smallVariants"
* molecular.smallVariants.identifier 1..1 string "identifier" "A base identifier type."
* molecular.smallVariants.genes 0..* BackboneElement "genes" "genes"
* molecular.smallVariants.genes.code 0..1 string "code" "HGNC:ID"
* molecular.smallVariants.localization 0..* BackboneElement "localization" "localization"
* molecular.smallVariants.localization.code 0..1 code "code" "Gene localization"
* molecular.smallVariants.gdnaChange 0..1 string "gdnaChange" "gDNA change (HGVS)."
* molecular.smallVariants.cdnaChange 0..1 string "cdnaChange" "cDNA change (HGVS)."
* molecular.smallVariants.proteinChange 0..1 string "proteinChange" "Protein change (HGVS)."
* molecular.smallVariants.acmgClass 0..1 code "acmgClass" "ACMG class."
* molecular.smallVariants.acmgCriteria 0..* BackboneElement "acmgCriteria" "acmgCriteria"
* molecular.smallVariants.acmgCriteria.value 1..1 code "value" "value"
* molecular.smallVariants.acmgCriteria.modifier 0..1 code "modifier" "modifier"
* molecular.smallVariants.zygosity 0..1 code "zygosity" "Zygosity."
* molecular.smallVariants.segregationAnalysis 0..1 code "segregationAnalysis" "Segregation analysis."
* molecular.smallVariants.modeOfInheritance 0..1 code "modeOfInheritance" "modeOfInheritance"
* molecular.smallVariants.diagnosticSignificance 0..1 code "diagnosticSignificance" "Significance for case."
* molecular.smallVariants.externalId 0..1 string "externalId" "ClinVar variant ID."
* molecular.smallVariants.publications 0..* string "publications" "Reference[Publication]. e.g., PubMed ID"
* molecular.smallVariants.chromosome 1..1 code "chromosome" "chromosome"
* molecular.smallVariants.startPosition 1..1 integer "startPosition" "Start coordinate in GRCh38 VCF-style."
* molecular.smallVariants.endPosition 1..1 integer "endPosition" "End coordinate in GRCh38 VCF-style."
* molecular.smallVariants.ref 1..1 string "ref" "ref sequence VCF-style."
* molecular.smallVariants.alt 1..1 string "alt" "alt/observed sequence VCF-style."
* molecular.copyNumberVariants 0..* BackboneElement "copyNumberVariants" "copyNumberVariants"
* molecular.copyNumberVariants.identifier 1..1 string "identifier" "A base identifier type."
* molecular.copyNumberVariants.genes 0..* BackboneElement "genes" "genes"
* molecular.copyNumberVariants.genes.code 0..1 string "code" "HGNC:ID"
* molecular.copyNumberVariants.localization 0..* BackboneElement "localization" "localization"
* molecular.copyNumberVariants.localization.code 0..1 code "code" "Gene localization"
* molecular.copyNumberVariants.gdnaChange 0..1 string "gdnaChange" "gDNA change (HGVS)."
* molecular.copyNumberVariants.cdnaChange 0..1 string "cdnaChange" "cDNA change (HGVS)."
* molecular.copyNumberVariants.proteinChange 0..1 string "proteinChange" "Protein change (HGVS)."
* molecular.copyNumberVariants.acmgClass 0..1 code "acmgClass" "ACMG class."
* molecular.copyNumberVariants.acmgCriteria 0..* BackboneElement "acmgCriteria" "acmgCriteria"
* molecular.copyNumberVariants.acmgCriteria.value 1..1 code "value" "value"
* molecular.copyNumberVariants.acmgCriteria.modifier 0..1 code "modifier" "modifier"
* molecular.copyNumberVariants.zygosity 0..1 code "zygosity" "Zygosity."
* molecular.copyNumberVariants.segregationAnalysis 0..1 code "segregationAnalysis" "Segregation analysis."
* molecular.copyNumberVariants.modeOfInheritance 0..1 code "modeOfInheritance" "modeOfInheritance"
* molecular.copyNumberVariants.diagnosticSignificance 0..1 code "diagnosticSignificance" "Significance for case."
* molecular.copyNumberVariants.externalId 0..1 string "externalId" "ClinVar variant ID."
* molecular.copyNumberVariants.publications 0..* string "publications" "Reference[Publication]. e.g., PubMed ID"
* molecular.copyNumberVariants.chromosome 1..1 code "chromosome" "chromosome"
* molecular.copyNumberVariants.startPosition 1..1 integer "startPosition" "GRCh38 coordinate VCF-style."
* molecular.copyNumberVariants.endPosition 1..1 integer "endPosition" "GRCh38 coordinate VCF-style."
* molecular.copyNumberVariants.type 1..1 code "type" "type"
* plan 0..1 BackboneElement "plan" "plan"
* plan.carePlanRd 1..1 BackboneElement "carePlanRd" "carePlanRd"
* plan.carePlanRd.molecularBoardDecisionDate 1..1 date "molecularBoardDecisionDate" "Date of the case conference."
* plan.carePlanRd.studyRecommended 1..1 boolean "studyRecommended" "Recommendation for participation in a clinical study."
* plan.carePlanRd.counsellingRecommended 1..1 boolean "counsellingRecommended" "Recommendation for human genetic counseling."
* plan.carePlanRd.reEvaluationRecommended 1..1 boolean "reEvaluationRecommended" "Recommendation for re-evaluation."
* plan.carePlanRd.therapyRecommended 1..1 boolean "therapyRecommended" "Recommendation for therapy."
* plan.carePlanRd.clinicalManagementRecommended 1..1 boolean "clinicalManagementRecommended" "Recommendations for clinical management."
* plan.carePlanRd.clinicalManagementDescriptions 0..* code "clinicalManagementDescriptions" "clinicalManagementDescriptions"
* plan.recommendedStudies 0..* BackboneElement "recommendedStudies" "recommendedStudies"
* plan.recommendedStudies.identifier 1..1 string "identifier" "A base identifier type."
* plan.recommendedStudies.register 1..1 code "register" "Study register with priority to NCT if multiple entries exist."
* plan.recommendedStudies.name 1..1 string "name" "Name of the recommended study."
* plan.recommendedStudies.id 1..1 string "id" "id"
* plan.recommendedStudies.variants 0..* string "variants" "variants"
* plan.recommendedTherapies 0..* BackboneElement "recommendedTherapies" "recommendedTherapies"
* plan.recommendedTherapies.identifier 1..1 string "identifier" "A base identifier type."
* plan.recommendedTherapies.type 1..1 code "type" "Description of the recommended therapy."
* plan.recommendedTherapies.strategy 1..1 code "strategy" "Description of the recommended therapy strategy."
* plan.recommendedTherapies.strategyOther 0..1 string "strategyOther" "Description of the recommended therapy only if 'other' is selected."
* plan.recommendedTherapies.strategyCombination 0..1 string "strategyCombination" "Description of the recommended therapy only if'combination' is selected."
* plan.recommendedTherapies.variants 0..* string "variants" "variants"
* followUp 0..1 BackboneElement "followUp" "followUp"
* followUp.followUpRds 1..* BackboneElement "followUpRds" "For each of the several followups, a new object with the current status is created."
* followUp.followUpRds.followUpDate 1..1 date "followUpDate" "Follow-up date in YYYY-MM-DD format."
* followUp.followUpRds.phenotypes 1..* Coding "phenotypes" "phenotypes"
* followUp.followUpRds.gmfcs 0..1 code "gmfcs" "GMFCS level. Leave empty if not applicable."
* followUp.followUpRds.diagnosisEstablished 1..1 boolean "diagnosisEstablished" "diagnosisEstablished"
* followUp.followUpRds.diseaseProgression 0..1 string "diseaseProgression" "Case-relevant supplementary data on the progression of the disease."
* followUp.followUpRds.vitalStatus 1..1 code "vitalStatus" "Vital status at the last contact."
* followUp.followUpRds.deathDate 0..1 string "deathDate" "Month and year of death in YYYY-MM format."
