Logical: KdkSubmissionMetaData
Id: kdk-submission-meta-data
Title: "KDK Submission/MetaData – Quellmodell (BfArM MVGenomSeq)"
Description: "Quelltreues Logical Model der KDK-Submission-Metadaten (metaData). Quelle fuer StructureMap metaData -> MII Person + Consent."
* ^status = #draft
* submission 1..1 BackboneElement "submission" "submission"
* submission.date 1..1 date "date" "Date of submission in ISO 8601 format YYYY-MM-DD"
* submission.type 1..1 code "type" "The options are: 'initial' for first submission, 'followup' is for followup submissions, 'addition' for additional submission, 'correction' for correction, 'test' is for technical testing of submissions"
* submission.submitterId 1..1 string "submitterId" "LE ID as specified by the BfArM or RVO"
* submission.genomicDataCenterId 0..1 string "genomicDataCenterId" "Id of the genomic data center, format GRZXXXnnn 9-digit assigned by BfArM. Not required in cases where diagnosisOd.libraryType = none."
* submission.clinicalDataNodeId 1..1 string "clinicalDataNodeId" "Id of the clinical data node, format KDKXXXnnn 9-digit assigned by BfArM"
* submission.diseaseType 1..1 code "diseaseType" "Type of disease (must be oncological or hereditary for Oncology object, rare for RareDiseasesObject)"
* mvConsent 1..1 BackboneElement "mvConsent" "mvConsent"
* mvConsent.presentationDate 0..1 date "presentationDate" "Date of delivery. Date (in ISO 8601 format YYYY-MM-DD) on which the Model Project Declaration of Participation was presented to the patient, unless identical to the date of signature"
* mvConsent.version 1..1 string "version" "Version of the declaration of participation. Name and version of the declaration of participation in the MV GenomSeq, e.g.: 'Patient Info TE Consent MVGenomSeq vers01'"
* mvConsent.scope 1..* BackboneElement "scope" "Modules of the consent to MV: must have at least a permit of mvSequencing"
* mvConsent.scope.type 1..1 code "type" "Consent or refusal to participate and consent, must be indicated for each option listed in the scope of consent."
* mvConsent.scope.date 1..1 date "date" "Date of signature of the pilot projects consent; in ISO 8601 format YYYY-MM-DD."
* mvConsent.scope.domain 1..1 code "domain" "Scope of consent or revocation."
* researchConsents 1..* BackboneElement "researchConsents" "Research consents. Multiple declarations of consent are possible! Must be assigned to the respective data sets."
* researchConsents.schemaVersion 0..1 code "schemaVersion" "Schema version of de.medizininformatikinitiative.kerndatensatz.consent"
* researchConsents.presentationDate 1..1 date "presentationDate" "Date of the delivery of the research consent in ISO 8601 format (YYYY-MM-DD)"
* researchConsents.scope 0..1 BackboneElement "scope" "Scope of the research consent in JSON format following the MII IG Consent v2025 FHIR schema. See 'https://www.medizininformatik-initiative.de/Kerndatensatz/KDS_Consent_V2025/MII-IG-Modul-Consent.html' and 'https://packag"
* researchConsents.noScopeJustification 0..1 code "noScopeJustification" "Justification if no scope object is present."
* coverageType 1..1 code "coverageType" "Health insurance providers"
* tanC 1..1 string "tanC" "Transaction number VNk"
* localCaseId 0..1 string "localCaseId" "A local case identifier of the Leistungserbringer to be able to track multiple submissions referring to the same index patient"
* gender 1..1 code "gender" "gender"
* birthDate 1..1 string "birthDate" "Date of birth without the day. Format YYYY-MM"
* addressAGS 1..1 string "addressAGS" "Official municipal code of the patient's residence."
* decisionToInclude 1..1 boolean "decisionToInclude" "Decision of the multidisciplinary case conference in the field of diagnostics on the inclusion of the insured person in the pilot project"
* molecularBoardDecisionDate 1..1 date "molecularBoardDecisionDate" "Date of the decision of the multidisciplinary case conference in the field of diagnostics on the inclusion of the insured person in the pilot project"
* rejectionJustification 0..1 code "rejectionJustification" "Reason for the negative decision"
