Logical: MvgsKdkOncologyModel
Id: mvgs-kdk-oncology-model
Title: "MVGS KDK Onkologie – Logisches Modell"
Description: "Logisches Modell zur Dokumentation der KDK-Onkologie-Datenstruktur im Modellvorhaben Genomsequenzierung. Bildet die hierarchische Struktur der JSON-Übermittlung ab."
Characteristics: #can-be-target
* submission 1..1 BackboneElement "Übermittlung" "Metadaten der Übermittlung"
  * submissionDate 1..1 date "Übermittlungsdatum" "Datum der Übermittlung"
  * submissionType 1..1 code "Übermittlungsart" "Art der Übermittlung (initial, followup, correction)"
  * transactionNumber 1..1 string "Vorgangsnummer" "Eindeutige Vorgangsnummer"
  * softwareName 0..1 string "Software" "Name der übermittelnden Software"
  * softwareVersion 0..1 string "Softwareversion" "Version der übermittelnden Software"
* patient 1..1 BackboneElement "Patient" "Patientendaten"
  * pseudonym 1..1 string "Pseudonym" "Patienten-Pseudonym"
  * gender 1..1 code "Geschlecht" "Geschlecht des Patienten"
  * birthDate 1..1 date "Geburtsdatum" "Geburtsdatum (YYYY-MM)"
  * postalCode 0..1 string "PLZ" "Postleitzahl oder AGS"
  * coverageType 0..1 code "Versicherungsart" "Art der Krankenversicherung"
* case 1..1 BackboneElement "Fall" "Falldaten"
  * diagnosis 1..1 BackboneElement "Diagnose" "Diagnosedaten"
    * icd10gm 1..1 code "ICD-10-GM" "ICD-10-GM-Code"
    * icd10gmVersion 1..1 string "ICD-10-GM Version" "Version des ICD-10-GM-Katalogs"
    * histologyIcdO3 0..1 code "Histologie (ICD-O-3)" "ICD-O-3 Histologie-Code"
    * topographyIcdO3 0..1 code "Topographie (ICD-O-3)" "ICD-O-3 Topographie-Code"
    * onsetDate 1..1 date "Erstdiagnose" "Datum der Erstdiagnose"
  * priorDiagnostics 0..* BackboneElement "Vordiagnostik" "Vorangegangene diagnostische Maßnahmen"
    * type 1..1 code "Art" "Art der Vordiagnostik"
    * date 0..1 date "Datum" "Datum der Vordiagnostik"
    * result 0..1 string "Ergebnis" "Ergebnis der Vordiagnostik"
  * priorProcedures 0..* BackboneElement "Vortherapie" "Vorangegangene therapeutische Maßnahmen"
    * type 1..1 code "Art" "Art der Vortherapie"
    * startDate 0..1 date "Beginn" "Beginn der Vortherapie"
    * endDate 0..1 date "Ende" "Ende der Vortherapie"
* molecular 0..1 BackboneElement "Molekulare Befunde" "Molekulargenetische Befunde"
  * smallVariants 0..* BackboneElement "Kleine Varianten" "SNV und kleine Indels"
    * gene 1..1 code "Gen" "HGNC-Gen-Symbol"
    * hgvsCDna 0..1 string "HGVSc" "HGVS DNA-Nomenklatur"
    * hgvsProtein 0..1 string "HGVSp" "HGVS Protein-Nomenklatur"
    * chromosome 0..1 code "Chromosom" "Chromosom"
    * genomicSource 1..1 code "Genomische Herkunft" "Somatisch oder Keimbahn"
  * cnv 0..* BackboneElement "CNV" "Kopienzahlvarianten"
    * gene 0..1 code "Gen" "Betroffenes Gen"
    * type 1..1 code "Typ" "Art der CNV (Amplifikation, Deletion)"
    * copyNumber 0..1 integer "Kopienzahl" "Kopienzahl"
  * structuralVariants 0..* BackboneElement "Strukturvarianten" "Fusionen und andere Strukturvarianten"
    * gene1 0..1 code "Gen 1" "Erstes Fusionsgen"
    * gene2 0..1 code "Gen 2" "Zweites Fusionsgen"
    * type 1..1 code "Typ" "Art der Strukturvariante"
  * expression 0..* BackboneElement "Expression" "Genexpressionsdaten"
    * gene 1..1 code "Gen" "Untersuchtes Gen"
    * result 1..1 string "Ergebnis" "Expressionsergebnis"
  * biomarker 0..* BackboneElement "Biomarker" "Weitere Biomarker"
    * name 1..1 string "Bezeichnung" "Name des Biomarkers"
    * value 1..1 string "Wert" "Wert des Biomarkers"
* plan 0..1 BackboneElement "Therapieplan" "MTB-Therapieplan"
  * boardDecisionDate 0..1 date "MTB-Datum" "Datum der MTB-Entscheidung"
  * studyRecommended 0..1 boolean "Studienempfehlung" "Empfehlung zur Studienteilnahme"
  * counsellingRecommended 0..1 boolean "Beratungsempfehlung" "Empfehlung zur genetischen Beratung"
  * reEvaluationRecommended 0..1 boolean "Re-Evaluierung" "Empfehlung zur erneuten Evaluation"
  * interventionRecommended 0..1 boolean "Intervention" "Empfehlung zur therapeutischen Intervention"
* followUp 0..* BackboneElement "Verlauf" "Verlaufsdaten"
  * date 1..1 date "Datum" "Verlaufsdatum"
  * status 1..1 code "Status" "Verlaufsstatus"
  * therapy 0..1 BackboneElement "Therapie" "Durchgeführte Therapie"
    * type 0..1 code "Therapietyp" "Art der Therapie"
    * startDate 0..1 date "Beginn" "Therapiebeginn"
    * endDate 0..1 date "Ende" "Therapieende"
